language: python
python:
  - "2.7"
  - "3.6"

env:
  - PLATFORMIO_PROJECT_DIR=examples/mbed-blink
  - PLATFORMIO_PROJECT_DIR=examples/mbed-rtos-ethernet
  - PLATFORMIO_PROJECT_DIR=examples/zephyr-blink
  - PLATFORMIO_PROJECT_DIR=examples/zephyr-synchronization

# Zephyr framework doesn't support python 2
jobs:
  exclude:
    - python: "2.7"
      env: PLATFORMIO_PROJECT_DIR=examples/zephyr-blink
    - python: "2.7"
      env: PLATFORMIO_PROJECT_DIR=examples/zephyr-synchronization

install:
  - pip install -U https://github.com/platformio/platformio/archive/develop.zip
  - platformio platform install file://.

script:
  - platformio run -d $PLATFORMIO_PROJECT_DIR

notifications:
  email: false
